### PR TITLE
Friendlier message when `cxx::CxxString` is used in a `#[cxx::bridge]`.

### PR DESCRIPTION
**Pull request by anforowicz**

### CODE REVIEW

**Comment by anforowicz** [comment]
@adetaylor, can you PTAL?

This hopefully addresses at least one pain point that was discussed in the internal chat at https://chat.google.com/room/AAAAk1UCFGg/8ipDlSk4rvs

I am not sure if I am 100% happy with the new error message - feel free to propose changes if appropriate.

**Comment by zetafunction** [comment]
Is there any way to suggest a clang-style fix-it hint to remove the cxx:: qualifier? I guess that should be implied by the message but it wouldn't hurt.

**Comment by anforowicz** [comment]
> Is there any way to suggest a clang-style fix-it hint to remove the cxx:: qualifier? I guess that should be implied by the message but it wouldn't hurt.

I don't see anything explicitly documented for [`syn::Error`](https://docs.rs/syn/latest/syn/struct.Error.html).  And it seems that compiler folks [say](https://internals.rust-lang.org/t/crate-for-outputting-rust-compiler-style-errors/20573/2) that [`annotate_snippets`](https://docs.rs/annotate-snippets/latest/annotate_snippets/) may be one option - maybe `cxx` can use something like this in the future?

Since I didn't hear any violent objections against the current error message, I think I'll go ahead and turn this into a `cxx` PR.

**Comment by anforowicz** [comment]
This has been now merged upstream.

**Pull request closed without merging**
